version: '3'

services:
  profiledb:
    image: postgres:latest
    volumes:
      - ./.ignore/postgres/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - NEW_POSTGRES_NAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5436:80"
  web:
    build: .
    command: ["sh", "scripts/start.sh"]
    volumes:
      - .:/code
    ports:
      - "8002:8000"
    depends_on:
      - profiledb