# Generated by Django 2.2.5 on 2019-10-11 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='username',
            field=models.CharField(blank=True, default='', max_length=50, unique=True),
        ),
    ]
